/**
 * ATW capability library — the health functions, ingredients and formats we
 * can develop through our manufacturing and ingredient partners.
 *
 * Editorial rules for this file:
 *  - Partner and supplier identities are confidential. Never name a factory,
 *    parent company, city or branded/trademarked ingredient here — list the
 *    generic ingredient instead (e.g. "Cactus Extract", not a brand of it).
 *  - No health or medical claims. Function names describe a positioning a
 *    customer might formulate toward; ingredient entries are names only.
 *  - Ingredient names are kept in their common trade-generic form so they can
 *    be searched by a customer who already knows what they want.
 */

export interface CapabilityFunction {
  id: string;
  name: string;
  blurb: string;
  ingredients: string[];
}

export interface CapabilityFormat {
  name: string;
  desc: string;
  examples: string[];
}

export const FUNCTIONS: CapabilityFunction[] = [
  {
    id: "brain",
    name: "Brain & Focus",
    blurb: "Nootropic-style positionings built around focus, clarity and cognitive nutrition.",
    ingredients: [
      "Alpha Lipoic Acid",
      "Astaxanthin",
      "Bilberry Extract",
      "Centella Asiatica Extract",
      "Colostrum Milk Powder",
      "DHA Powder",
      "DHA & EPA (Omega-3)",
      "Gynostemma Pentaphyllum",
      "L-Cysteine / N-Acetyl L-Cysteine",
      "L-Lysine",
      "Phosphatidylserine",
      "Quercetin",
      "Resveratrol",
      "Soy Lecithin",
      "Tart Cherry Extract",
      "Turmeric Extract",
      "Walnut Peptide",
    ],
  },
  {
    id: "sleep",
    name: "Sleep & Relaxation",
    blurb: "Evening rituals, calming blends and rest-oriented products.",
    ingredients: [
      "Ashwagandha Extract",
      "Griffonia Seed Extract",
      "Gynostemma Pentaphyllum",
      "Holy Basil Extract",
      "L-Glycine",
      "Reishi Mushroom Extract",
      "Saffron Extract",
      "Tart Cherry Extract",
      "Valerian Root Extract",
      "Walnut Peptide",
      "Zinc",
    ],
  },
  {
    id: "immunity",
    name: "Immunity",
    blurb: "Daily-defence positionings using mushrooms, botanicals, vitamins and cultures.",
    ingredients: [
      "Acai Berry Extract",
      "Andrographis Extract",
      "Artichoke Leaf Extract",
      "Ascorbic Acid (Vitamin C)",
      "Astaxanthin",
      "Colostrum Milk Powder",
      "Elderberry Extract",
      "Gynostemma Pentaphyllum",
      "Honeysuckle Extract",
      "Lactobacillus Rhamnosus",
      "Lactoferrin",
      "L-Cysteine / N-Acetyl L-Cysteine",
      "Liposomal Vitamin C",
      "Papaya Leaf Extract",
      "Pine Pollen Extract",
      "Probiotics",
      "Reishi Mushroom Extract",
      "Soy Peptide",
      "Tiger Milk Mushroom",
      "Vitamin E",
      "Yeast Beta Glucan",
    ],
  },
  {
    id: "gut",
    name: "Gut, Digestive & Fibre",
    blurb: "Probiotic, prebiotic, enzyme and fibre products for everyday digestive comfort.",
    ingredients: [
      "Artichoke Leaf Extract",
      "Boswellia Extract",
      "Corn Fibre (Resistant Dextrin)",
      "Digestive Enzyme Premix",
      "Fermented Soy",
      "Fructo-oligosaccharide (FOS)",
      "Galacto-oligosaccharide (GOS)",
      "Green Kiwi Fruit Extract",
      "Inulin",
      "Isomalto-oligosaccharide (IMO)",
      "Konjac Fibre",
      "L-Cysteine / N-Acetyl L-Cysteine",
      "Mulberry Leaf Extract",
      "Multigrain Powder",
      "Oat Beta Glucan",
      "Oat Fibre",
      "Oil Palm Fibre",
      "Postbiotics",
      "Prebiotics",
      "Probiotics",
      "Psyllium Husk",
      "Soy Lecithin",
      "Wheat Fibre",
      "Xylo-oligosaccharide (XOS)",
    ],
  },
  {
    id: "antioxidant",
    name: "Antioxidant",
    blurb: "Berry, botanical and polyphenol-led blends for antioxidant positionings.",
    ingredients: [
      "Acai Berry Extract",
      "Acerola Cherry Extract",
      "Alpha Lipoic Acid",
      "Artichoke Leaf Extract",
      "Ascorbic Acid (Vitamin C)",
      "Astaxanthin",
      "Bilberry Extract",
      "Bitter Melon Extract",
      "Blackberry Powder",
      "Black Garlic Extract",
      "Blueberry Powder",
      "Cactus Extract",
      "Capsicum Extract",
      "Centella Asiatica Extract",
      "Coenzyme Q10",
      "Cranberry Extract",
      "Grape Seed Extract",
      "Green Tea Extract",
      "Gynostemma Pentaphyllum",
      "Hovenia Dulcis Fruit Extract",
      "L-Cysteine / N-Acetyl L-Cysteine",
      "Mangosteen Extract",
      "Mulberry Leaf Extract",
      "Pine Bark Extract",
      "Pine Pollen Extract",
      "Plum Powder",
      "Reishi Mushroom Extract",
      "Resveratrol",
      "Sacha Inchi",
      "Vitamin E",
      "Walnut Peptide",
    ],
  },
  {
    id: "beauty",
    name: "Beauty & Skin",
    blurb: "Collagen, ceramide and botanical beauty-from-within drinks and capsules.",
    ingredients: [
      "Apple & Grape Stem Cell Extract",
      "Ascorbic Acid (Vitamin C)",
      "Astaxanthin",
      "Bird's Nest Extract",
      "Camu Camu Extract",
      "Chitin Extract",
      "Collagen Tripeptides",
      "Crassocephalum Rabens Extract",
      "Eggshell Membrane",
      "Hyaluronic Acid",
      "Hydrolyzed Fish Collagen Peptide",
      "L-Cysteine / N-Acetyl L-Cysteine",
      "L-Glutathione",
      "Liposomal Vitamin C",
      "Lycopene Extract",
      "Melon Extract",
      "Pomegranate Extract",
      "Rice Ceramide",
      "Rose Petal Extract",
      "Sakura Extract",
      "Silk Peptide",
      "Torula Yeast",
      "Tremella Extract",
      "White Pomegranate Extract",
      "White Tomato Extract",
      "Yeast Ceramide",
    ],
  },
  {
    id: "aging",
    name: "Healthy Aging",
    blurb: "Longevity-oriented formulations from NMN to traditional mushrooms.",
    ingredients: [
      "Astaxanthin",
      "Black Sesame",
      "Coenzyme Q10",
      "Eggshell Membrane",
      "Grape Seed Extract",
      "Gynostemma Pentaphyllum",
      "L-Cysteine / N-Acetyl L-Cysteine",
      "Melon Extract",
      "Nicotinamide Mononucleotide (NMN)",
      "Pine Pollen Extract",
      "Reishi Mushroom Extract",
      "Resveratrol",
      "Soy Peptides",
    ],
  },
  {
    id: "weight",
    name: "Weight Management",
    blurb: "Slimming, satiety and metabolism-led drinks, blends and meal replacements.",
    ingredients: [
      "Apple Cider Vinegar Powder",
      "Astaxanthin",
      "Bitter Hops Extract",
      "Bitter Melon Extract",
      "Black Garlic Extract",
      "Blood Orange Extract",
      "Brown Seaweed Extract",
      "Cactus Extract",
      "Capsicum Extract",
      "Citrus Polyphenol Extract",
      "Conjugated Linoleic Acid (CLA)",
      "Garcinia Cambogia Extract",
      "Green Coffee Bean Extract",
      "Gymnema Sylvestre Extract",
      "Gynostemma Pentaphyllum",
      "Hovenia Dulcis Fruit Extract",
      "L-Carnitine",
      "Okra Powder",
      "Protein Concentrate",
      "White Kidney Bean Extract",
    ],
  },
  {
    id: "protein",
    name: "Protein & Plant Proteins",
    blurb: "Dairy and plant protein bases for shakes, meal replacements and plant milks.",
    ingredients: [
      "Almond Protein",
      "Corn Peptide",
      "Pea Protein",
      "Protein Concentrate",
      "Rice Protein",
      "Soy Peptides",
      "Soy Protein",
      "Walnut Peptide",
      "Walnut Protein",
      "Wheat Protein",
      "Whey Protein",
    ],
  },
  {
    id: "bone",
    name: "Bone & Joint",
    blurb: "Calcium, collagen and botanical formulations for mobility positionings.",
    ingredients: [
      "Boswellia Extract",
      "Calcium Carbonate",
      "Calcium Citrate",
      "Carnosine",
      "Chitin Extract",
      "Chondroitin",
      "Cinnamon Extract",
      "Coenzyme Q10",
      "Collagen Tripeptide",
      "Collagen Type II",
      "Colostrum Milk Powder",
      "Curcumin Extract",
      "Glucosamine",
      "Magnesium",
      "Medium Chain Triglycerides (MCT)",
      "Resveratrol",
      "Seaweed Calcium",
      "Tart Cherry Extract",
      "Vitamin D3",
      "Vitamin K",
      "Willow Bark Extract",
    ],
  },
  {
    id: "vision",
    name: "Vision",
    blurb: "Carotenoid and berry blends for eye-care positionings.",
    ingredients: [
      "Astaxanthin",
      "Beta Carotene",
      "Bilberry Extract",
      "Eyebright Extract",
      "Fermented Berries Extract",
      "Lutein",
      "Marigold Extract",
      "Zeaxanthin",
    ],
  },
  {
    id: "men",
    name: "Men's Health",
    blurb: "Vitality blends built on Southeast Asian and Andean botanicals.",
    ingredients: [
      "Catuaba Extract",
      "Cordyceps Sinensis Extract",
      "L-Arginine",
      "Lycopene Extract",
      "Maca Extract",
      "Pine Pollen Extract",
      "Saw Palmetto Extract",
      "Tongkat Ali Extract",
      "Tribulus Terrestris Extract",
      "Zinc",
    ],
  },
  {
    id: "women",
    name: "Women's Health",
    blurb: "Feminine wellness formulations using traditional Malaysian herbs and beyond.",
    ingredients: [
      "Cranberry Extract",
      "Epimedium Extract",
      "Kacip Fatimah Extract",
      "Maca Extract",
      "Manjakani Extract",
      "Pine Pollen Extract",
      "Pueraria Lobata",
      "Pueraria Mirifica",
      "Resveratrol",
      "Rhodiola Rosea Extract",
      "Wild Yam Extract",
    ],
  },
  {
    id: "glucose",
    name: "Glucose Control",
    blurb: "Sugar-conscious formulations and low-glycaemic positionings.",
    ingredients: [
      "Bitter Melon Extract",
      "Chromium",
      "Cinnamon Extract",
      "Gymnema Sylvestre Extract",
      "Misai Kucing Extract",
      "Mulberry Leaf Extract",
      "Resistant Dextrin",
      "Stevia",
    ],
  },
  {
    id: "liver",
    name: "Liver Health",
    blurb: "Botanical liver-care positionings, from milk thistle to local herbs.",
    ingredients: [
      "Antrodia Cinnamomea",
      "Artichoke Leaf Extract",
      "Astaxanthin",
      "Bilberry Extract",
      "Bitter Melon Extract",
      "Cactus Extract",
      "Corn Peptide",
      "Dandelion Extract",
      "Green Tea Extract",
      "Gynostemma Pentaphyllum",
      "Hovenia Dulcis Fruit Extract",
      "L-Cysteine / N-Acetyl L-Cysteine",
      "Milk Thistle Extract",
      "Phyllanthus Amarus Extract",
      "Soy Lecithin",
      "Turmeric Extract",
    ],
  },
  {
    id: "heart",
    name: "Heart & Circulation",
    blurb: "Cardio-wellness blends built on garlic, ginger, omega-3 and fermented rice.",
    ingredients: [
      "Apple Cider Vinegar Powder",
      "Black Garlic Extract",
      "Coenzyme Q10",
      "DHA & EPA (Omega-3)",
      "Ginger Powder",
      "Green Tea Extract",
      "Red Yeast Rice",
      "Soy Lecithin",
      "Spirulina",
    ],
  },
  {
    id: "sport",
    name: "Energy, Sport & Muscle",
    blurb: "Pre-workout, hydration, recovery and energy drink formulations.",
    ingredients: [
      "Arabica Coffee",
      "B Vitamins",
      "Cordyceps Sinensis Extract",
      "Electrolyte Minerals",
      "Glycerol",
      "L-Carnitine",
      "L-Leucine",
      "Maca Extract",
      "Medium Chain Triglycerides (MCT)",
      "Panax Ginseng Extract",
      "Taurine",
      "Vitamin & Mineral Premix",
      "Whey Protein",
    ],
  },
  {
    id: "detox",
    name: "Detox & Cleansing",
    blurb: "Green, fibre and chlorophyll-based cleansing drinks.",
    ingredients: [
      "Dandelion Extract",
      "Digestive Enzyme Premix",
      "Green Tea Extract",
      "Liquid Chlorophyll",
      "Oil Palm Fibre",
      "Probiotics",
      "Psyllium Husk",
      "Spirulina",
      "Vegetable & Fruit Powder",
      "Wheatgrass Powder",
    ],
  },
];

export const CAPABILITY_FORMATS: CapabilityFormat[] = [
  {
    name: "Drink powders & fruit-powder blends",
    desc: "The most flexible base — almost any function above can be carried in a fruit-powder drink.",
    examples: ["Sachet drink mixes", "Fruit powder bases", "Greens & superfood blends"],
  },
  {
    name: "Functional coffee",
    desc: "Instant coffee formats with a wellness angle layered in.",
    examples: ["Latte, mocha & cappuccino", "White coffee", "Durian coffee", "Alkaline coffee"],
  },
  {
    name: "Milk tea",
    desc: "Instant milk tea premixes across flavour and functional directions.",
    examples: ["Matcha", "Hazelnut & peach", "Rose & sweet potato", "Spirulina"],
  },
  {
    name: "Cocoa & chocolate drinks",
    desc: "Indulgent chocolate bases carrying functional ingredients.",
    examples: ["Hot chocolate", "Cocoa oat", "Chocolate meal replacement"],
  },
  {
    name: "Plant & alternative milks",
    desc: "Dairy and dairy-alternative powdered milks with functional additions.",
    examples: ["Goat milk", "Soy milk", "Oat milk", "Colostrum milk"],
  },
  {
    name: "Multigrain & meal replacement",
    desc: "Satiety-led powders with protein, fibre and vitamin premixes.",
    examples: ["Multigrain powders", "Chocolate, strawberry & vanilla shakes"],
  },
  {
    name: "Sport & energy premixes",
    desc: "Hydration, pre-workout and recovery drink powders.",
    examples: ["Energy drink powders", "Electrolyte drinks", "Muscle recovery blends"],
  },
  {
    name: "Tablets",
    desc: "Compressed tablets for supplements and chewables.",
    examples: ["Vitamin C tablets", "Colostrum tablets", "Spirulina tablets"],
  },
  {
    name: "Capsules",
    desc: "Capsule supplements for herbal, beauty and general wellness lines.",
    examples: ["Traditional herb capsules", "Beauty capsules", "Health supplement capsules"],
  },
  {
    name: "Liquids",
    desc: "Liquid concentrates and ready-to-dilute formats.",
    examples: ["Liquid chlorophyll", "Mint & fruit variants"],
  },
];

/** Every unique ingredient across all functions, with the functions it appears in. */
export interface IngredientEntry {
  name: string;
  functions: CapabilityFunction[];
}

export const INGREDIENTS: IngredientEntry[] = (() => {
  const map = new Map<string, CapabilityFunction[]>();
  for (const fn of FUNCTIONS) {
    for (const ing of fn.ingredients) {
      const list = map.get(ing) ?? [];
      list.push(fn);
      map.set(ing, list);
    }
  }
  return Array.from(map.entries())
    .map(([name, functions]) => ({ name, functions }))
    .sort((a, b) => a.name.localeCompare(b.name, "en", { sensitivity: "base" }));
})();

export const CAPABILITY_STATS = {
  functions: FUNCTIONS.length,
  ingredients: INGREDIENTS.length,
  formats: CAPABILITY_FORMATS.length,
};
